CONF_FILE=$1
CURRENT_DIR=$PWD
PARENT_DIR="$(dirname "$PWD")"
TMP_DIR=$PARENT_DIR/tmp
OUT_DIR=$PARENT_DIR/out-release
DURATION=10
GYRO_DONATION_ADDR=Cuk6qKME6Kg1EAtZy7uJvQ97U8xajMEwy3nZCzq4tcJW7uANPcNk2pv5GiJPjj3NxdF8KA288AYwZaMrFWKhCvY73oQoZcu

LD_LIBRARY_PATH=$OUT_DIR/lib \
 $OUT_DIR/bin/gyrod \
 --data-dir $CURRENT_DIR/data1 \
 --log-level 1 \
 --p2p-bind-port 20000 \
 --rpc-bind-port 20001 \
 --zmq-rpc-bind-port 20002 \
 --rpc-login user1:123 \
 --add-exclusive-node 127.0.0.1:20010 \
 --no-igd \
 --allow-local-ip \
 --DURATION_TARGET=$DURATION \
 --EMISSION_SUBSIDY_PER_MINUTE=10 \
 --FINAL_SUBSIDY_PER_MINUTE=3000000000 \
 --CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX=71 \
 --CRYPTONOTE_PUBLIC_SUBADDRESS_BASE58_PREFIX=103 \
 --CRYPTONOTE_PUBLIC_INTEGRATED_ADDRESS_BASE58_PREFIX=72 \
 --CRYPTONOTE_MESSAGE_TX_LIVETIME=1800 \
 --CRYPTONOTE_DANDELIONPP_ENABLE_OPT=0 \
 --SPINNER_ENERGY_COST_MULTIPLIER=100000 \
 --SPINNER_PVRB_BLOCK_WINDOW=5 \
 --SPINNER_SPIN_BLOCK_WINDOW=500 \
 --GYRO_DONATION_ADDR=$GYRO_DONATION_ADDR \
 --generate-genesis-tx $CONF_FILE

LD_LIBRARY_PATH=$OUT_DIR/lib \
 $OUT_DIR/bin/gyrod \
 --testnet \
 --data-dir $CURRENT_DIR/data1 \
 --log-level 1 \
 --p2p-bind-port 20000 \
 --rpc-bind-port 20001 \
 --zmq-rpc-bind-port 20002 \
 --rpc-login user1:123 \
 --add-exclusive-node 127.0.0.1:20010 \
 --no-igd \
 --allow-local-ip \
 --DURATION_TARGET=$DURATION \
 --EMISSION_SUBSIDY_PER_MINUTE=10 \
 --FINAL_SUBSIDY_PER_MINUTE=3000000000 \
 --CRYPTONOTE_MESSAGE_TX_LIVETIME=1800 \
 --CRYPTONOTE_DANDELIONPP_ENABLE_OPT=0 \
 --SPINNER_ENERGY_COST_MULTIPLIER=100000 \
 --SPINNER_PVRB_BLOCK_WINDOW=5 \
 --SPINNER_SPIN_BLOCK_WINDOW=1000 \
 --GYRO_DONATION_ADDR=$GYRO_DONATION_ADDR \
 --generate-genesis-tx $CONF_FILE

LD_LIBRARY_PATH=$OUT_DIR/lib \
 $OUT_DIR/bin/gyrod \
 --stagenet \
 --data-dir $CURRENT_DIR/data1 \
 --log-level 1 \
 --p2p-bind-port 20000 \
 --rpc-bind-port 20001 \
 --zmq-rpc-bind-port 20002 \
 --rpc-login user1:123 \
 --add-exclusive-node 127.0.0.1:20010 \
 --no-igd \
 --allow-local-ip \
 --DURATION_TARGET=$DURATION \
 --EMISSION_SUBSIDY_PER_MINUTE=10 \
 --FINAL_SUBSIDY_PER_MINUTE=3000000000 \
 --CRYPTONOTE_MESSAGE_TX_LIVETIME=1800 \
 --CRYPTONOTE_DANDELIONPP_ENABLE_OPT=0 \
 --SPINNER_ENERGY_COST_MULTIPLIER=100000 \
 --SPINNER_PVRB_BLOCK_WINDOW=5 \
 --SPINNER_SPIN_BLOCK_WINDOW=1000 \
 --GYRO_DONATION_ADDR=$GYRO_DONATION_ADDR \
 --generate-genesis-tx $CONF_FILE
